name: IronLog
options:
  bundleIdPrefix: com.syntaxis
  deploymentTarget:
    iOS: '17.0'
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.10
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0
    DEVELOPMENT_TEAM: ''
packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    exactVersion: 2.5.1
  SDWebImageSwiftUI:
    url: https://github.com/SDWebImage/SDWebImageSwiftUI
    exactVersion: 3.1.1
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    exactVersion: 2.4.0
  KeychainSwift:
    url: https://github.com/evgenyneu/keychain-swift
    exactVersion: 21.0.0
  Reachability:
    url: https://github.com/ashleymills/Reachability.swift
    exactVersion: 5.2.0
  Privy:
    url: https://github.com/privy-io/privy-ios
    exactVersion: 2.8.0
  Reown:
    url: https://github.com/reown-com/reown-swift
    exactVersion: 2.2.2
  Starscream:
    url: https://github.com/daltoniam/Starscream
    exactVersion: 3.1.2
  Web3:
    url: https://github.com/Boilertalk/Web3.swift
    exactVersion: 0.8.8
  CryptoSwift:
    url: https://github.com/krzyzanowskim/CryptoSwift.git
    exactVersion: 1.8.3
targets:
  IronLog:
    type: application
    platform: iOS
    sources:
      - path: IronLog
        excludes:
          - Resources/Assets.xcassets/AppIcon.appiconset/.DS_Store
    resources:
      - path: IronLog/Resources
    info:
      path: IronLog/Info.plist
      properties:
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIBackgroundModes:
          - fetch
          - remote-notification
        NSPhotoLibraryUsageDescription: IronLog uses photos and videos to illustrate your exercise techniques.
        NSCameraUsageDescription: IronLog uses the camera to capture exercise demonstration media.
        CFBundleDisplayName: IronLog
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLName: com.syntaxis.ironlog.auth
            CFBundleURLSchemes:
              - ironlog
        LSApplicationQueriesSchemes:
          - metamask
          - rainbow
          - trust
          - zerion
          - cbwallet
          - wallet
          - wc
        REOWN_PROJECT_ID: 8ce707b5d51eae9d998ba388bc924999
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.syntaxis.ironlog
        TARGETED_DEVICE_FAMILY: 1,2
        GENERATE_INFOPLIST_FILE: false
        INFOPLIST_FILE: IronLog/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: IronLog/IronLog.entitlements
    dependencies:
      - package: Supabase
        product: Supabase
      - package: SDWebImageSwiftUI
        product: SDWebImageSwiftUI
      - package: MarkdownUI
        product: MarkdownUI
      - package: KeychainSwift
        product: KeychainSwift
      - package: Reachability
        product: Reachability
      - package: Privy
        product: Privy
      - package: Reown
        product: ReownAppKit
      - package: Reown
        product: WalletConnectNetworking
      - package: Reown
        product: WalletConnect
      - package: Starscream
        product: Starscream
      - package: Web3
        product: Web3
      - package: CryptoSwift
        product: CryptoSwift
  IronLogTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - IronLogTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
    dependencies:
      - target: IronLog
  IronLogUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - IronLogUITests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
    dependencies:
      - target: IronLog
